plugin: aws_ec2
regions:
  - eu-west-2
keyed_groups:
  - key: tags.Name
    prefix: tag
  - key: placement.availability_zone
    prefix: az
filters:
  tag:Role: webserver
  instance-state-name: running
hostnames:
  - public_ip_address
strict: False