name: EKS CI/CD Pipeline

on:
  push:
    branches: [main]
  pull_request:

env:
  AWS_REGION: eu-west-2
  EKS_CLUSTER_NAME: drupal-cluster
  DOCKER_IMAGE: drupal-ha-app
  DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}

jobs:
  deploy:
    name: Deploy to EKS
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Setup kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: '1.27.0'

      - name: Setup Helm
        uses: azure/setup-helm@v3

      - name: Update Kubeconfig
        run: |
          aws eks update-kubeconfig --region $AWS_REGION --name $EKS_CLUSTER_NAME

      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@v2
        with:
          organization: ${{ secrets.SONAR_ORG }}
          projectKey: ${{ secrets.SONAR_PROJECT_KEY }}
          token: ${{ secrets.SONAR_TOKEN }}

      - name: Login to Docker Hub
        run: |
          echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

      - name: Build and Push Docker Image to Docker Hub
        run: |
          IMAGE=${{ secrets.DOCKERHUB_USERNAME }}/$DOCKER_IMAGE
          docker build -t $IMAGE:latest ./docker
          docker push $IMAGE:latest

      - name: Update Kubernetes manifests with Docker Hub image
        run: |
          IMAGE=${{ secrets.DOCKERHUB_USERNAME }}/$DOCKER_IMAGE
          sed -i "s|image: .*|image: $IMAGE:latest|" k8s/deployment.yaml

      - name: Deploy Kubernetes Manifests
        run: |
          kubectl apply -f k8s/namespace.yaml
          kubectl apply -f k8s/configmap.yaml
          kubectl apply -f k8s/secret.yaml
          kubectl apply -f k8s/deployment.yaml
          kubectl apply -f k8s/service.yaml

      - name: Deploy Monitoring Stack with Helm
        run: |
          bash monitoring/helm-install.sh
